export const LABELS = {
  AUTH: {
    LOGIN_TITLE: 'Bienvenido de vuelta',
    LOGIN_SUBTITLE: 'Inicia sesión para continuar tu viaje',
    LOGIN_BUTTON: 'Iniciar sesión',
    REGISTER_TITLE: 'Crear cuenta',
    REGISTER_BUTTON: 'Registrar',
    LOGOUT_BUTTON: 'Salir',
    EMAIL: 'Email',
    PASSWORD: 'Contraseña',
    USERNAME: 'Usuario',
    FORGOT_PASSWORD: '¿Olvidaste tu contraseña?',
    FORGOT_PASSWORD_TITLE: 'Recuperar contraseña',
    HAVE_ACCOUNT: '¿Ya tienes cuenta? Inicia sesión',
    CREATE_ACCOUNT: 'Crear cuenta nueva',
    BACK_TO_HOME: 'Volver al inicio',
    SEND: 'Enviar',
  },
  FLIGHTS: {
    PAGE_TITLE: 'Encuentra tu vuelo perfecto',
    PAGE_SUBTITLE: 'Busca y reserva vuelos en tiempo real con las mejores aerolíneas',
    ORIGIN: 'Origen',
    DESTINATION: 'Destino',
    DATE: 'Fecha de viaje',
    SEARCH_BUTTON: 'Buscar vuelos',
    AVAILABLE_FLIGHTS: 'Vuelos disponibles',
    ROUTE: 'Ruta',
    FLIGHT_ROUTE: 'Ruta de vuelo',
    NO_FLIGHTS_TITLE: 'No hay vuelos disponibles',
    NO_FLIGHTS_MESSAGE: 'Intenta con otros criterios de búsqueda',
    SEARCH_TO_START: 'Busca vuelos para comenzar',
    SELECT_CRITERIA: 'Selecciona origen, destino y fecha',
    RESERVE: 'Reservar',
    PRICE: 'Precio',
    NO_PRICE: 'Sin precio',
    ON_TIME: 'A tiempo',
    DELAY: 'Retraso',
    MINUTES: 'min',
    TERMINAL: 'Terminal',
    GATE: 'Puerta',
    BELT: 'Cinta',
  },
  RESERVATIONS: {
    PAGE_TITLE: 'Mis reservas',
    PAGE_SUBTITLE: 'Gestiona tus vuelos reservados',
    NO_RESERVATIONS_TITLE: 'No tienes reservas aún',
    NO_RESERVATIONS_MESSAGE: '¡Comienza a explorar vuelos y reserva tu próxima aventura!',
    SEARCH_FLIGHTS: 'Buscar vuelos',
    FLIGHT: 'Vuelo',
    DATES: 'Fechas',
    STATUS: 'Estado',
    ACTIONS: 'Acciones',
    ACTIVE: 'Activa',
    CANCELLED: 'Cancelada',
    PAY: 'Pagar',
    CANCEL: 'Cancelar',
    SEAT: 'Asiento',
    CANCEL_DIALOG_TITLE: 'Cancelar Reserva',
    CANCEL_DIALOG_MESSAGE: '¿Estás seguro que deseas cancelar esta reserva? Esta acción no se puede deshacer.',
    CANCEL_DIALOG_CONFIRM: 'Sí, cancelar',
    CANCEL_DIALOG_CANCEL: 'No, mantener',
    VIEW_RESERVATIONS: 'Ver mis reservas',
  },
  LANDING: {
    HERO_TITLE: 'Tu próxima aventura comienza aquí',
    HERO_SUBTITLE: 'Descubre los mejores vuelos al mejor precio. Reserva fácil, rápido y seguro.',
    START_NOW: 'Comenzar ahora',
    LOGIN: 'Iniciar sesión',
    WHY_CHOOSE_TITLE: '¿Por qué elegir AEROTICKETS?',
    WHY_CHOOSE_SUBTITLE: 'Ofrecemos la mejor experiencia en reserva de vuelos con tecnología de punta',
    FEATURE_GLOBAL_TITLE: 'Vuelos Globales',
    FEATURE_GLOBAL_DESC: 'Accede a miles de destinos en todo el mundo con las mejores aerolíneas.',
    FEATURE_SECURE_TITLE: 'Pago Seguro',
    FEATURE_SECURE_DESC: 'Transacciones protegidas con los más altos estándares de seguridad.',
    FEATURE_FAST_TITLE: 'Reserva Rápida',
    FEATURE_FAST_DESC: 'Encuentra y reserva tu vuelo ideal en minutos, sin complicaciones.',
    FEATURE_PRICE_TITLE: 'Mejores Precios',
    FEATURE_PRICE_DESC: 'Compara y encuentra las mejores ofertas para tu próximo viaje.',
    STAT_DESTINATIONS: 'Destinos disponibles',
    STAT_CUSTOMERS: 'Clientes satisfechos',
    STAT_SUPPORT: 'Soporte al cliente',
    CTA_TITLE: '¿Listo para despegar?',
    CTA_SUBTITLE: 'Únete a miles de viajeros que confían en nosotros para sus aventuras',
    CTA_BUTTON: 'Crear cuenta gratis',
    FOOTER_COPYRIGHT: '© 2024 AEROTICKETS. Todos los derechos reservados.',
  },
  NAVBAR: {
    FLIGHTS: 'Vuelos',
    MY_RESERVATIONS: 'Mis Reservas',
    LOGIN: 'Ingresar',
    REGISTER: 'Registrarse',
  },
  MODAL: {
    RESERVE_FLIGHT: 'Reserva tu vuelo',
    SELECT_SEAT: 'Selecciona tu asiento',
    AIRCRAFT_INFO: 'Información de la aeronave',
    SCHEDULE: 'Horario',
    AIRCRAFT: 'Aeronave',
    ROUTE_INFO: 'Ruta',
    GATE_INFO: 'Puerta',
  },
  PAYMENT: {
    TOTAL: 'Total a pagar:',
    CONFIRM_AND_PAY: 'Confirmar y pagar',
    CANCEL_BUTTON: 'Cancelar',
    AUTO_REDIRECT: 'Serás redirigido automáticamente en unos segundos...',
    TRY_AGAIN: 'Intentar nuevamente',
    PROCESSING: 'Procesando...',
    REDIRECTING: 'Redirigiendo...',
    CANCELING: 'Cancelando...',
  },
  COMMON: {
    UNKNOWN: 'Desconocida',
    UNKNOWN_SHORT: '—',
  },
} as const;
